### ISSUE TITLE
Tracing requests without logging results

### ISSUE THREAD

**Issue by dchambers** [DanielMSchmidt/apollo-opentracing#154]
H There, is there a way not to log the results as these will contain PII (Personally identifiable Information), which we're not allowed to log?

Thanks in advance.

**Comment by dchambers** [comment]
From looking at the code I can already see that this [isn't currently configurable](https://github.com/DanielMSchmidt/apollo-opentracing/blob/master/src/index.ts#L152). Would you accept a PR to add support for a `logResults` flag in the options provided to the `OpentracingExtension` constructor?

**Comment by DanielMSchmidt** [comment]
Hey @dchambers 

Yeah, this is a feature on my bucket list that I haven't got to 😢 

I think I would love to have some `onRequestFinish` and `onFieldResolveFinish` callbacks that get the result as an argument. Would it be possible for you to do a PR?

**Comment by dchambers** [comment]
Hi @DanielMSchmidt, can you took a look at #157 which hopefully addresses this issue in the way you describe.
