### ISSUE TITLE
Extending SpanContext in TypeScript

### ISSUE THREAD

**Issue by landau** [DanielMSchmidt/apollo-opentracing#248]
_When implementing my own context, is it expected to `extend` `SpanContext`?_

I ask because when importing `SpanContext` it is found in the subdirectory `'apollo-opentracing/dist/context'` rather than the index file. Reaching into subdirectories is often seen as an anti-pattern because the subdirs are considered  internal modules.

```ts
import { SpanContext } from 'apollo-opentracing/dist/context';
export interface MyResolverContext extends SpanContext {
  myCustomThing: CustomThing
}
```

When creating an instance of this extension, a client's context must be of type `SpanContext`.

```ts
const apolloServer = new ApolloServer({
    extensions: [(): OpenTracingExtension<MyResolverContext> => 
		new OpenTracingExtension({ server: tracer, local: tracer })]
});
```

The `addContextHelpers` function is also a useful implementation that clients should use that is in a nested dir. https://github.com/DanielMSchmidt/apollo-opentracing/blob/master/src/context.ts#L34-L50

Thanks for your time.

**Comment by DanielMSchmidt** [comment]
I expose the span context in this PR, could you take a look? https://github.com/DanielMSchmidt/apollo-opentracing/pull/259

**Comment by landau** [comment]
✅ Thanks!
