### ISSUE TITLE
How to use apollo-opentracing with graphql-yoga middlewares

### ISSUE THREAD

**Issue by jjLudin** [DanielMSchmidt/apollo-opentracing#295]
Hi @DanielMSchmidt, I want to use apollo-opentracing with my graphql-yoga server, but I see that you are using another form of applying this middleware (app.use()). Does this module support graphql-yoga middlewares? 

Using tracer (initTracer()) from: https://github.com/yurishkuro/opentracing-tutorial/tree/master/nodejs

Code (src/index.ts):
```javascript
const OpentracingExtension = require('apollo-opentracing').default;

const serverTracer = initTracer('serverTracer');

const localTracer = initTracer('localTracer');

const server = new GraphQLServer({
    schema,
    context,
    middlewares: [
        () =>
            new OpentracingExtension({
                server: serverTracer,
                local: localTracer
            })
    ]
});
```

Output:
```text
TypeError: String cannot represent value: { serverTracer: { _tags: [Object], _metrics: [Metrics], _serviceName: "serverTracer", _reporter: [CompositeReporter], _sampler: [ConstSampler], _logger: [Object], _baggageSetter: [BaggageSetter], _debugThrottler: [DefaultThrottler], _injectors: [Object], _extractors: [Object], _process: [Object], _traceId128bit: undefined, _shareRpcSpan: undefined }, localTracer: { _tags: [Object], _metrics: [Metrics], _serviceName: "localTracer", _reporter: [CompositeReporter], _sampler: [ConstSampler], _logger: [Object], _baggageSetter: [BaggageSetter], _debugThrottler: [DefaultThrottler], _injectors: [Object], _extractors: [Object], _process: [Object], _traceId128bit: undefined, _shareRpcSpan: undefined }, requestSpan: null, shouldTraceRequest:
[function alwaysTrue], shouldTraceFieldResolver: [function alwaysTrue], onFieldResolveFinish: undefined, onFieldResolve: undefined, onRequestResolve: [function emptyFunction] }
```

Any help is appreciated. Thanks!

**Comment by DanielMSchmidt** [comment]
Hey, I don't really understand where the error is coming from. Could you create a Node.js [Coesandbox](https://codesandbox.io/) with this example code set up, so that I can have a look at the actual error? That would be very helpful to me :)

**Comment by jjLudin** [comment]
Hi Daniel,

Apologies for the delay. My colleague made progress on this and ended up making our own middleware to inject the span into the GraphQL context. User: @rusher2004

We plan to create a project and document it to share with others. 

Thanks for your time. I'll close the issue.
