### ISSUE TITLE
Top level span names other than `request`

### ISSUE THREAD

**Issue by zekenie** [DanielMSchmidt/apollo-opentracing#306]
Hi,

I've been playing around with this for a bit, and I'm really liking it. Is there a way to name the top level spans something other than `request`? It would be far more useful for me if it were something like `{mutation|query}: {name}`.

Is this achievable? How might I go about configuring this?

Thank you!

**Comment by DanielMSchmidt** [comment]
Hey, I'm really sorry for the delay, this one slipped through the cracks 🙈 

I think this should be possible, I think your suggestion is way better than the "request" we currently have.

We set it [here](https://github.com/DanielMSchmidt/apollo-opentracing/blob/42ddc282a5bc4e3b51580bfddffb6e9902136403/src/index.ts#L145) and the method should have everything in place in the info params (https://github.com/DanielMSchmidt/apollo-opentracing/blob/42ddc282a5bc4e3b51580bfddffb6e9902136403/src/index.ts#L40)

Would you have the time to create a PR for this? I'll review it 😇

**Comment by zekenie** [comment]
Sure can. I can probably figure this out on my own, but maybe you already know the answer... How would I get the name of the mutation or query that's happening from the `RequestStart` object

```

export interface RequestStart<TContext> {
  request: Pick<Request, "url" | "method" | "headers">;
  queryString?: string;
  parsedQuery?: DocumentNode;
  operationName?: string;
  variables?: { [key: string]: any };
  persistedQueryHit?: boolean;
  persistedQueryRegister?: boolean;
  context: TContext;
  requestContext: GraphQLRequestContext<TContext>;
}
```

**Comment by sigginet** [comment]
We have the same issue - it makes it a lot trickier to find the right traces.
@DanielMSchmidt can you merge #313 ?
