### ISSUE TITLE
extensions deprecation

### ISSUE THREAD

**Issue by dorinsimionescu** [DanielMSchmidt/apollo-opentracing#330]
Hi,

The new apollo version will favor the new plugin api and extensions will be deprecated.

[deprecated] A "OpentracingExtension" was defined within the "extensions" configuration for Apollo Server.  The API on which this extension is built ("graphql-extensions") is being deprecated in the next major version of Apollo Server in favor of the new plugin API.  See https://go.apollo.dev/s/plugins for the documentation on how these plugins are to be defined and used.

Are there any plans to migrate the this project to use the new extensions api?

Thank you,
Dorin

**Comment by DanielMSchmidt** [comment]
Hi, I think we should make it a plugin as well. I haven't looked deeply into the plugin docs, but it seems like besides a bit of the interface not much changed, would you like to give it a try?

**Comment by robross0606** [comment]
Apollo has become pretty heavy-handed with their notifications on this one.  You get one of those messages on your application for each extension that is registered against Apollo.  No way to quiet them down.

**Comment by Multiply** [comment]
I'm going to be implementing OpenTracing in our next apollo project, so might pick this up if anyone still needs it

**Comment by robross0606** [comment]
We definitely need it, but I have not had time to work on a PR.

**Comment by oliversalzburg** [comment]
I'm also interested in this subject and would be willing to invest some time to work on porting this to a proper plugin.

We are currently using our own Apollo Server plugin in our stack. This plugin will simply export the existing Apollo traces into an external tracer (Jaeger in our case). But the additional features in this module seem interesting enough to revisit this.

Also note that there is apparently work in this area in the opentelemetry space: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/14

**Comment by Multiply** [comment]
@oliversalzburg thanks for the link.
I think a generic implementation is preferred, and not something bound to apollo-server specifically.

I'll follow the developments in opentelemetry-js-contrib more closely over the next two weeks, and if good progress is being made, I'll stick with their implementation.

**Comment by robross0606** [comment]
Bump

**Comment by oliversalzburg** [comment]
@robross0606 Did you have a look at https://github.com/open-telemetry/opentelemetry-js-contrib/pull/226 by any chance?

I just wrote my own Apollo plugins for tracing. You can easily convert the internally collected spans or collect your own. The tracing plugin in Apollo can be used as a base to work off.

However, the above PR looks most promising and I might try to convert to that approach.
