### ISSUE TITLE
subscriptions

### ISSUE THREAD

**Issue by RichardWright** [DanielMSchmidt/apollo-opentracing#382]
Hi

I can't find any mention of subscriptiopns, are these supported by this library? 

thanks for the great work!

**Comment by DanielMSchmidt** [comment]
I'm not 100% certain, but we hook into what apollo provides so I would assume we also trace subscriptions. I would assume the resolution only ends after the subscription closes, so probably you get pretty long traces

**Comment by RichardWright** [comment]
I suspect it will blow up here - https://github.com/DanielMSchmidt/apollo-opentracing/blob/master/src/index.ts#L134

my tests seem to be showing no request on a subscription context, only a connection.

**Comment by RichardWright** [comment]
Tried it with a small application. No sign of subscriptions. Where's a good place to start with the apollo server api?

**Comment by RichardWright** [comment]
Doesn't look good - https://github.com/apollographql/subscriptions-transport-ws/issues/781

**Comment by DanielMSchmidt** [comment]
Thanks for the heads up 👍
