### ISSUE TITLE
What is the point of local tracer and server tracer?

### ISSUE THREAD

**Issue by cliedeman** [DanielMSchmidt/apollo-opentracing#41]

**Comment by DanielMSchmidt** [comment]
> server: Only used for the root (the first span we will start)
local: Used to start every other span

I guess this explanation did not help you, right? So some tracer have this concept of client and server interaction, where we always when we cross borders of backends (e.g. through HTTP) talk about a client sending a request and a server receiving the request. If you have local actions within the backend you talk about local spans. 

To enable people with these kinds of tracers to use this library I wanted to make sure to have a clear separation here. There is one tracer with the job of tracing the server request, being the first one called and another tracer being used to trace within the service. If you have a very strict tracer it might be that you would even need a third kind of tracer in your resolvers which would be a client to be able to extract the http headers. 

Does this make sense? How could I have phrased the readme so this would be more clear to you?

**Comment by cliedeman** [comment]
Ha, I completely missed that text. I think its clear enough for someone who isn't speed reading. So in short its for fine grained tracing vs higher level aggregation? You could also place a comment where the tracers are consumed as I expected to find more info there

Side Note: So the root span which is created in a different tracer will still end up in the traces sampled from the local tracer?

**Comment by DanielMSchmidt** [comment]
No, not really. It has nothing to do with granularity, it is just that the server tracer is the one which takes the incoming http request and the local tracer traces within the backend. You need this distribution as some tracers are religious about having these two kinds of tracers and they won't trace a thing if you don't follow this pattern.

> So the root span which is created in a different tracer will still end up in the traces sampled from the local tracer?

You need to have the same backend for both tracers, otherwise, it won't work.

**Comment by cliedeman** [comment]
Thanks for all the information!

**Comment by DanielMSchmidt** [comment]
You are welcome

Ciaran Liedeman <notifications@github.com> schrieb am Do., 13. Sep. 2018,
13:45:
