### ISSUE TITLE
Write integration test

### ISSUE THREAD

**Issue by DanielMSchmidt** [DanielMSchmidt/apollo-opentracing#49]
Build a setup where tests are run against a configured version of `apollo-server` with a fake opentracing tracer to make sure that everything is started as it should be.

**Comment by cliedeman** [comment]
I started on one but didn't finish it. #50.

The tracer methods are called and that's where I stopped. Not sure if you want the tests to run at the http level but this is just one lower.

**Comment by cliedeman** [comment]
Created #62 to demonstrate the parent span issue

**Comment by DanielMSchmidt** [comment]
I think we did this one pretty well already 👍
