### ISSUE TITLE
bug: update default to use newest apollo-server-plugin-base

### ISSUE THREAD

**Issue by choroalfaro** [DanielMSchmidt/apollo-opentracing#520]
Hey guys!, this is my first time creating an issue. Sorry if this is not the right way.

Our teams is using the openTracing-plugin to trace on Apollo v2 on a previous repo, we are currently trying to use this on Apollo v3, but the apollo-server-plugin-base version used is not compatible with the used in Apollo v3.

Could you guys update it to use the new version? Changes seems to be mainly related to types.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/50691674/175144329-3f5aed8f-d9b7-4a4a-94ee-a1669108358e.png">

**Comment by TattdCodeMonkey** [comment]
@choroalfaro  This should be resolved with the [v3.0.0](https://github.com/DanielMSchmidt/apollo-opentracing/releases/tag/v3.0.0) release.
