### ISSUE TITLE
Use the renamed field name for a span if there is one

### ISSUE THREAD

**Issue by DanielMSchmidt** [DanielMSchmidt/apollo-opentracing#87]
Given this query

```graphql
{
  myAlias: field
}
```

You currently get a span with the name "field", where it should be "myAlias"

**Comment by cliedeman** [comment]
This probably means 
```
{
  alias1: field
  alias2: field
}
```

would break tracing too

**Comment by DanielMSchmidt** [comment]
Well, not break but they would not be distinguishable to my understanding

**Comment by cliedeman** [comment]
Ah I see. Maybe adding the alias to the span operation name might be enough then? 
I thought this would be difficult but I guess you just need to update this [line](https://github.com/DanielMSchmidt/apollo-opentracing/blob/master/src/index.ts#L111).

If I remember correctly [field nodes](https://github.com/graphql/graphql-js/blob/master/src/execution/execute.js#L688) always has a single entry and has the [alias](https://github.com/graphql/graphql-js/blob/master/src/language/ast.js#L248). I also have a nagging feeling in the back of my head that fragments are somehow involved too

**Comment by DanielMSchmidt** [comment]
Yeah, [this line](https://github.com/DanielMSchmidt/apollo-opentracing/blob/master/src/index.ts#L120) needs to be changed, want to do a PR for that?
