### ISSUE TITLE
Use tags instead of logs

### ISSUE THREAD

**Issue by cliedeman** [DanielMSchmidt/apollo-opentracing#91]
Things like [this](https://github.com/DanielMSchmidt/apollo-opentracing/blob/master/src/index.ts#L102) should likely be a tag instead of a log.
The rule of thumb I use is that things known at the start of the span should all be tags.

- [ ] Add tags to snapshot serializer
- [ ] log/tag variables
- [ ] field resolver tags (fieldName, fieldType)

The graphql-go package has a [good reference](https://github.com/graph-gophers/graphql-go/blob/master/trace/trace.go#L55) for tags

**Comment by DanielMSchmidt** [comment]
Good idea, let's do it 👍
